# example file for building sonar with prometheus and grafana
version: "3.0"
services:
  sonar:
    build: .
    volumes:
      - sonar-grafana-dashboards:/opt/sonar/dashboards
    networks:
      - sonar
    ports:
      - 4200:8080
  prometheus:
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus:latest
    depends_on:
      - sonar
    ports:
      - 4201:9090
    networks:
      - sonar
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/sonar-prometheus.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/sonar.yaml
      - sonar-grafana-dashboards:/var/lib/grafana/dashboards/
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/sonar.json
    ports:
      - 4202:3000
    networks:
      - sonar

networks:
  sonar:

volumes:
  sonar-grafana-dashboards:
