# example file for building sonar with prometheus and grafana
version: "3.0"
services:
  sonar:
    build: .
    networks:
      - sonar
    ports:
      - 4200:8080
  prometheus:
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus:latest
    ports:
      - 4201:9090
    networks:
      - sonar
  grafana:
    image: grafana/grafana:latest
    ports:
      - 4203:3000
    networks:
      - sonar

networks:
  sonar:
